namespace: hferreira23
name: pihole
version: 0.1.3
readme: README.md
authors:
  - Hugo Ferreira
description: |
  A collection of modules for managing your Pi-hole installation.
license:
  - MIT
tags:
  - pihole
  - dns
  - linux
  - networking
dependencies: {}
repository: https://github.com/hferreira23/pihole-ansible
build_ignore:
  - roles
  - dist
  - .ansible
  - .vscode
  - .github
  - .gitignore
