---
namespace: hferreira23
name: pihole
version: "1.1.2"
readme: README.md
authors:
  - Shane Barbetta
description: >
  A collection of modules for managing your Pi-hole installation.
license:
  - "MIT"
tags:
  - pihole
  - dns
  - linux
dependencies: {}
repository: https://github.com/hferreira23/pihole-ansible
build_ignore:
  - roles/
